on:
  push:
    branches:
      - 'main'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version from VERSION.txt
        id: version
        run: echo "::set-output name=VERSION::$(cat VERSION.txt)"
      - name: Get changelog
        id: changelog
        run: echo "::set-output name=CHANGELOG::$(npx changelog-parser | jq -r '.versions[] | select(.version=="${{ steps.version.outputs.VERSION }}").body')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Test v${{ steps.version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
